default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

local_default: &local_default
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASS', 'postgres') %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  <<: *local_default
  database: To_Do_List_Api_development

test:
  <<: *default
  <<: *local_default
  database: To_Do_List_Api_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host:     <%= ENV['DB_HOST'] %>
  url:      <%= ENV['DB_URL'] %>
  port:     <%= ENV['DB_PORT'] %>
